import { COLORS } from "../../common/constants";

export const styles = {
  loginPage: {
    width: "100%",
    minHeight: "100vh",
    position: "relative",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    isolation: "isolate",
    boxSizing: "border-box",
    fontFamily: '"Arial", sans-serif',
    color: COLORS.sidebarBg,
    textAlign: "left",
    // Only reset box-sizing — do NOT zero padding/margin on all descendants
    "&, & *": {
      boxSizing: "border-box",
    },
    // Keep login buttons consistent with page font
    "& button": {
      fontFamily: '"Arial", sans-serif',
      textTransform: "none",
      boxShadow: "none",
    },
    "& h1, & h2, & h3": {
      margin: 0,
      lineHeight: 1.25,
    },
    "&::before": {
      content: '""',
      position: "absolute",
      inset: 0,
      background: "var(--login-bg) center / cover no-repeat",
      zIndex: -2,
    },
    "&::after": {
      content: '""',
      position: "absolute",
      inset: 0,
      background: "rgba(255, 255, 255, 0.18)",
      backdropFilter: "blur(18px) saturate(1.4)",
      WebkitBackdropFilter: "blur(18px) saturate(1.4)",
      zIndex: -1,
    },
    "@media (max-width: 900px)": {
      padding: "30px 15px",
      overflowY: "auto",
    },
  },

  loginCard: {
    width: "1100px",
    height: "590px",
    background: "#f0f1f6",
    borderRadius: "12px",
    position: "relative",
    zIndex: 2,
    display: "flex",
    overflow: "hidden",
    boxShadow: "0 25px 45px rgba(0, 0, 0, 0.15)",
    "&::before": {
      content: '""',
      position: "absolute",
      top: "50%",
      left: "50%",
      width: "52%",
      height: "92%",
      transform: "translate(-50%, -50%)",
      backgroundImage: "var(--content-left-bg)",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center center",
      backgroundSize: "contain",
      zIndex: 0,
      pointerEvents: "none",
    },
    "@media (max-width: 1200px)": {
      width: "90%",
    },
    "@media (max-width: 900px)": {
      height: "auto",
      flexDirection: "column",
    },
  },
  leftStrip: {
    position: "relative",
    zIndex: 1,
    width: "10px",
    height: "100%",
    background: "#151b2c",
    flexShrink: 0,
  },
  contentLeft: {
    width: "62%",
    padding: "70px 40px 40px 65px",
    position: "relative",
    zIndex: 1,
    isolation: "isolate",
    overflow: "hidden",
    "&::after": {
      content: '""',
      position: "absolute",
      inset: 0,
      background: "rgba(255, 255, 255, 0.22)",
      backdropFilter: "blur(3px) saturate(1.3)",
      WebkitBackdropFilter: "blur(16px) saturate(1.3)",
      zIndex: -1,
    },
    "@media (max-width: 900px)": {
      width: "100%",
      padding: "35px",
    },
  },
  contentLeftHeading: {
    position: "relative",
    zIndex: 1,
    fontSize: "28px",
    lineHeight: 1.25,
    color: "#071511",
    fontWeight: 800,
    marginBottom: "30px",
    marginTop: 0,
  },
  loginImg: {
    position: "relative",
    zIndex: 1,
    width: "530px",
    maxWidth: "100%",
    display: "block",
    marginTop: "30px",
  },
  contentRight: {
    position: "relative",
    zIndex: 1,
    width: "38%",
    padding: "78px 95px 40px 35px",
    background: "rgba(255, 255, 255, 0.22)",
    backdropFilter: "blur(3px) saturate(1.3)",
    WebkitBackdropFilter: "blur(16px) saturate(1.3)",
    "@media (max-width: 900px)": {
      width: "100%",
      padding: "35px",
    },
  },
  loginBox: {
    width: "315px",
    height: "310px",
    background: COLORS.sidebarBg,
    padding: "32px 28px",
    "@media (max-width: 900px)": {
      width: "100%",
    },
  },
  loginBoxHeading: {
    color: "#ffffff",
    textAlign: "center",
    fontSize: "15px",
    fontWeight: 600,
    marginBottom: "18px",
  },
  loginForm: {
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column" as const,
  },
  inputStack: {
    marginTop: "14px",
  },
  fieldWrap: {
    display: "flex",
    flexDirection: "column" as const,
  },
  errorSlot: {
    minHeight: "16px",
    fontSize: "11px",
    color: "#d32f2f",
    lineHeight: 1.3,
    paddingTop: "2px",
    paddingLeft: "2px",
  },
  inputGroup: {
    height: "55px",
    padding: "9px 10px",
    border: "1px solid #d8d8df",
  },
  inputLabel: {
    display: "block",
    fontSize: "11px",
    fontWeight: 800,
    marginBottom: "3px",
  },
  inputField: {
    width: "100%",
    border: "none",
    outline: "none",
    background: "transparent",
    fontSize: "13px",
    padding: 0,
    margin: 0,
    fontFamily: "inherit",
    "&::placeholder": {
      color: "#8d93a1",
      fontWeight: 600,
    },
  },
  whiteInput: {
    background: "#ffffff",
    color: COLORS.sidebarBg,
  },
  whiteInputField: {
    color: COLORS.sidebarBg,
  },
  darkInput: {
    background: COLORS.sidebarBg,
    color: "#ffffff",
    borderTop: "1px solid #d8d8df",
    marginTop: 0,
  },
  darkInputField: {
    color: "#ffffff",
  },
  loginButton: {
    width: "100%",
    height: "48px",
    marginTop: "15px",
    backgroundColor: COLORS.primary,
    border: "none !important",
    borderRadius: "3px",
    color: "#161616 !important",
    fontSize: "15px",
    fontWeight: 800,
    cursor: "pointer",
    padding: "0 !important",
    boxShadow: "none !important",
    "&:hover": {
      backgroundColor: COLORS.sidebarHoverBg,
      color: "#ffffff",
      border: "none !important",
      boxShadow: "none !important",
    },
    "&.Mui-disabled": {
      backgroundColor: COLORS.primary,
      color: "#ffffff",
      opacity: 0.7,
    },
  },
  copyright: {
    marginTop: "50px",
    fontSize: "11px",
    color: "#1f2433",
    textAlign: "left",
    "@media (max-width: 900px)": {
      marginTop: "25px",
    },
  },
  copyrightSpan: {
    color: "#006ee6",
  },
  bottomPanel: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: "56%",
    height: "245px",
    background: COLORS.sidebarBg,
    zIndex: 1,
    paddingTop: "102px",
    paddingLeft: "100px",
    textAlign: "left",
    "@media (max-width: 900px)": {
      display: "none",
    },
  },
  bottomPanelHeading: {
    color: "#ffffff",
    fontSize: "36px",
    fontWeight: 400,
    letterSpacing: "2px",
    margin: 0,
    paddingTop: "12px",
    display: "block",
  },
  yellowLine: {
    width: "165px",
    height: "16px",
    background: COLORS.primary,
    borderRadius: "3px",
    marginTop: "30px",
    marginLeft: "360px",
  },
};
