import { COLORS } from "../../common/constants";
import { MOBILE_MAX } from "../../common/constants/breakpoints";

export const styles = {
  pageShell: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "14px",
    width: "100%",
    height: "100%",
    minHeight: 0,
    boxSizing: "border-box" as const,
  },
  loadingWrap: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    minHeight: "400px",
  },
  tabs: {
    minHeight: "40px",
    flexShrink: 0,
    borderBottom: "1px solid rgba(15, 23, 41, 0.1)",
    "& .MuiTabs-indicator": {
      height: "3px",
      backgroundColor: COLORS.primary,
    },
    "& .MuiTab-root": {
      minHeight: "40px",
      padding: "8px 14px",
      textTransform: "none" as const,
      fontSize: "13px",
      fontWeight: 600,
      color: "rgba(15, 23, 41, 0.62)",
      letterSpacing: "0.01em",
    },
    "& .MuiTab-root.Mui-selected": {
      color: COLORS.primary,
      fontWeight: 700,
    },
  },
  sectionPanel: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
    flex: "1 1 auto",
    minHeight: "400px",
    height: "400px",
  },
  tableShell: {
    width: "100%",
    flex: "1 1 auto",
    minHeight: 0,
    borderRadius: "8px",
    border: "1px solid rgba(15, 23, 41, 0.1)",
    backgroundColor: COLORS.white,
    overflow: "hidden" as const,
    display: "flex",
    flexDirection: "column" as const,
  },
  table: {
    width: "100%",
    tableLayout: "fixed" as const,
    flex: "1 1 auto",
    "& .MuiTableCell-root": {
      textAlign: "center !important" as const,
      verticalAlign: "middle",
    },
  },
  headerRow: {
    backgroundColor: "rgba(15, 23, 41, 0.04)",
  },
  headerCell: {
    fontWeight: 700,
    fontSize: "12px",
    color: COLORS.sidebarBg,
    borderBottom: "1px solid rgba(15, 23, 41, 0.12)",
    padding: "6px 8px !important",
    textAlign: "center !important" as const,
    verticalAlign: "middle" as const,
    boxSizing: "border-box" as const,
    letterSpacing: "0.02em",
  },
  headerCellCenter: {
    textAlign: "center !important" as const,
  },
  dataRow: {
    height: "48px",
    "&:last-child td": {
      borderBottom: "none",
    },
  },
  deletedDataRow: {
    height: "48px",
    "&:last-child td": {
      borderBottom: "none",
    },
    "& td": {
      color: "#9e9e9e !important",
    },
  },
  dataCell: {
    fontSize: "12px",
    fontWeight: 400,
    lineHeight: 1.3,
    color: COLORS.textPrimary,
    padding: "4px 8px !important",
    borderBottom: "1px solid rgba(15, 23, 41, 0.08)",
    textAlign: "center !important" as const,
    verticalAlign: "middle" as const,
    boxSizing: "border-box" as const,
    wordBreak: "break-word" as const,
    whiteSpace: "normal" as const,
  },
  dataCellCenter: {
    textAlign: "center !important" as const,
    verticalAlign: "middle" as const,
  },
  descriptionCell: {
    width: "34%",
  },
  descriptionText: {
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    overflow: "hidden" as const,
    wordBreak: "break-word" as const,
    textAlign: "center" as const,
    margin: "0 auto",
    maxWidth: "100%",
    lineHeight: 1.3,
  },
  dateCell: {
    width: "33%",
  },
  actorCell: {
    width: "33%",
  },
  commentDateCell: {
    width: "33.33%",
  },
  commentAuthorCell: {
    width: "33.33%",
  },
  commentContentCell: {
    width: "33.34%",
  },
  commentsColumnWidths: ["33.33%", "33.33%", "33.34%"] as const,
  logsColumnWidths: ["33.33%", "33.33%", "33.34%"] as const,
  uploadedFilesColumnWidths: [
    "18%",
    "20%",
    "13%",
    "15%",
    "14%",
    "20%",
  ] as const,
  fileNameCell: {
    width: "18%",
  },
  emailCell: {
    width: "20%",
  },
  mobileCell: {
    width: "13%",
  },
  uploadedByCell: {
    width: "15%",
  },
  uploadedOnCell: {
    width: "14%",
  },
  actionCell: {
    width: "20%",
    whiteSpace: "nowrap" as const,
    verticalAlign: "middle" as const,
  },
  actionButtonsWrap: {
    display: "grid",
    gridTemplateColumns: "40px 40px 40px",
    columnGap: "4px",
    alignItems: "center",
    justifyItems: "center",
    width: "128px",
    margin: "0 auto",
  },
  actionIconSlot: {
    width: "40px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  actionDeleteSlot: {
    width: "40px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  actionIconButton: {
    minWidth: "32px !important",
    width: "32px !important",
    height: "32px !important",
    padding: "0 !important",
    flexShrink: 0,
  },
  deletedChip: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    height: "24px",
    width: "40px",
    padding: "0",
    margin: 0,
    borderRadius: "6px",
    backgroundColor: "rgba(209, 91, 6, 0.12)",
    color: `${COLORS.primary} !important`,
    fontWeight: "600 !important",
    fontSize: "9px !important",
    lineHeight: "1.2 !important",
    boxSizing: "border-box" as const,
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  oldChip: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    height: "24px",
    padding: "0 8px",
    borderRadius: "6px",
    backgroundColor: "rgba(15, 23, 41, 0.08)",
    color: "rgba(15, 23, 41, 0.65) !important",
    fontWeight: "600 !important",
    fontSize: "11px !important",
    lineHeight: "1.2 !important",
    fontStyle: "italic" as const,
    boxSizing: "border-box" as const,
    whiteSpace: "nowrap" as const,
  },
  emptyState: {
    margin: 0,
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "28px 16px",
    textAlign: "center" as const,
    fontSize: "13px",
    color: "rgba(51, 51, 51, 0.65)",
    borderRadius: "8px",
    border: "1px dashed rgba(15, 23, 41, 0.14)",
    backgroundColor: "rgba(15, 23, 41, 0.02)",
    boxSizing: "border-box" as const,
  },
  paginationWrap: {
    flexShrink: 0,
    minHeight: "52px",
    width: "100%",
  },
  paginationExternal: {
    padding: "4px 0",
  },
  footerActions: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingTop: "12px",
    borderTop: "1px solid rgba(15, 23, 41, 0.1)",
    flexShrink: 0,
  },
  closeButton: {
    minWidth: "120px",
    height: "40px",
    backgroundColor: COLORS.primary,
    border: "none !important",
    borderRadius: "8px",
    color: `${COLORS.white} !important`,
    fontSize: "13px",
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase" as const,
    cursor: "pointer",
    padding: "0 22px !important",
    boxShadow: "none !important",
    "&:hover": {
      backgroundColor: "#b34d05",
      color: COLORS.white,
      boxShadow: "none !important",
    },
  },
} as const;

/** Popup chrome used only by Upload History entry points. */
export const uploadHistoryPopupStyles = {
  paper: {
    width: "min(860px, 92vw) !important",
    maxWidth: "860px !important",
    minWidth: "min(720px, 92vw)",
    height: "min(720px, calc(100vh - 32px))",
    maxHeight: "calc(100vh - 32px)",
    borderRadius: "12px",
    overflow: "hidden",
    backgroundColor: COLORS.white,
    boxShadow: "0 18px 40px rgba(15, 23, 41, 0.16)",
    display: "flex",
    flexDirection: "column" as const,
  },
  header: {
    backgroundColor: COLORS.white,
    borderBottom: "1px solid rgba(15, 23, 41, 0.1)",
    minHeight: "52px",
    padding: "10px 16px",
    flexShrink: 0,
  },
  content: {
    padding: "16px 20px 18px",
    backgroundColor: "#fafbfc",
    overflow: "hidden",
    overflowY: "hidden",
    overflowX: "hidden",
    flex: "1 1 auto",
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
    [`@media (max-width: ${MOBILE_MAX}px)`]: {
      padding: "12px 14px 14px",
    },
  },
} as const;
