export const styles = {
  header: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    width: "100%",
    backgroundColor: "#fff",
    zIndex: 1000,
    padding: "16px 12px",
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    borderBottom: "1px solid #e0e0e0",
    boxSizing: "border-box" as const,
  },
  leftEmblem: {
    width: "90px",
    height: "72px",
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    flexShrink: 0,
  },
  leftEmblemImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain" as const,
  },
  centerContent: {
    display: "flex",
    fontFamily: "system-ui, Avenir, Helvetica, Arial, sans-serif",
    flexDirection: "column" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    flex: 1,
    minWidth: 0,
    padding: "0 8px",
  },
  title: {
    fontSize: "26px",
    fontWeight: "bold",
    color: "#000",
    margin: 0,
    lineHeight: 1.3,
    letterSpacing: "1px",
    textAlign: "center" as const,
  },
  subtitle: {
    fontSize: "16px",
    fontWeight: "normal",
    color: "#000",
    margin: "4px 0 0 0",
    lineHeight: 1.3,
    letterSpacing: "1px",
    textAlign: "center" as const,
  },
  rightEmblem: {
    width: "90px",
    height: "72px",
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    flexShrink: 0,
  },
  rightEmblemImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain" as const,
  },
};
