export const styles = {
  header: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    width: "100%",
    backgroundColor: "#fff",
    zIndex: 1000,
    padding: "10px 10px",
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    borderBottom: "1px solid #e0e0e0",
  },
  leftEmblem: {
    width: "100px",
    height: "80px",
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  leftEmblemImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain" as const,
  },
  centerContent: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    flex: 1,
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#000",
    margin: 0,
    lineHeight: 1.3,
    letterSpacing: "1px",
    textAlign: "center" as const,
  },
  subtitle: {
    fontSize: "18px",
    fontWeight: "normal",
    color: "#000",
    margin: "4px 0 0 0",
    lineHeight: 1.3,
    letterSpacing: "1px",
    textAlign: "center" as const,
  },
  rightEmblem: {
    width: "100px",
    height: "80px",
    display: "flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  rightEmblemImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain" as const,
  },
};
