export const ENDPOINTS = {
  LOGIN: "/api/login",
  APPROVERS_LIST: "/api/approvers-list",
  APPLICATION_DETAILS: "/api/application-details",
  ASSIGN_APPLICATION: "/api/assign-application",
  INSPECTION_APPROVERS: "/api/inspection-approvers",
  SEND_FOR_APPROVAL: "/api/send-for-approval",
  UPLOAD_INSPECTION_FILE: "/api/upload-inspection-file",
  UPLOAD_HISTORY: "/api/upload-history",
  INSPECTION_COMMENTS: "/api/inspection-comments",
  DOWNLOAD_INSPECTION_FILE: "/api/download-inspection-file",
  DOWNLOAD_HISTORY_FILE: "/api/download-history-file",
  DELETE_INSPECTION_FILE: "/api/delete-inspection-file",
  COMPLETE_APPLICATION: "/api/complete-application",
} as const;
