import { COLORS } from "../../common/constants";
import { MOBILE_MAX } from "../../common/constants/breakpoints";
import { styles as selectApproverStyles } from "../select-approver/style";

export const styles = {
  ...selectApproverStyles,
  pageShell: {
    width: "100%",
    margin: "0 auto",
  },
  uploadForm: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "18px",
    width: "100%",
    maxWidth: "720px",
    margin: "0 auto",
  },
  section: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  sectionEyebrow: {
    margin: 0,
    color: "rgba(15, 23, 41, 0.55)",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
  },
  fieldSection: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  fieldLabel: {
    color: COLORS.textPrimary,
    fontSize: "14px",
    fontWeight: 600,
  },
  documentTypeSelect: {
    borderRadius: "10px",
    backgroundColor: COLORS.white,
    "& .MuiOutlinedInput-notchedOutline": {
      borderColor: "rgba(15, 23, 41, 0.14)",
    },
    "&:hover .MuiOutlinedInput-notchedOutline": {
      borderColor: `${COLORS.primary} !important`,
    },
    "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
      borderColor: `${COLORS.primary} !important`,
      borderWidth: "1.5px",
    },
    "&.Mui-focused .MuiSvgIcon-root": {
      color: COLORS.primary,
    },
    "& .MuiSelect-select": {
      fontSize: "14px",
      color: COLORS.textPrimary,
      padding: "12px 14px",
    },
  },
  documentTypeMenu: {
    "& .MuiMenuItem-root:hover": {
      backgroundColor: "rgba(209, 91, 6, 0.08)",
    },
    "& .MuiMenuItem-root.Mui-selected": {
      backgroundColor: "rgba(209, 91, 6, 0.12) !important",
      color: COLORS.primary,
    },
    "& .MuiMenuItem-root.Mui-selected:hover": {
      backgroundColor: "rgba(209, 91, 6, 0.2) !important",
    },
    "& .MuiMenuItem-root.Mui-selected.Mui-focusVisible": {
      backgroundColor: "rgba(209, 91, 6, 0.12) !important",
    },
    "& .MuiMenuItem-root.Mui-focusVisible": {
      backgroundColor: "rgba(209, 91, 6, 0.08)",
    },
  },
  placeholderText: {
    color: "rgba(51, 51, 51, 0.55)",
  },
  uploadPanel: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    padding: "14px 16px",
    borderRadius: "12px",
    border: "1px dashed rgba(15, 23, 41, 0.18)",
    backgroundColor: COLORS.white,
    boxSizing: "border-box" as const,
    [`@media (max-width: ${MOBILE_MAX}px)`]: {
      flexDirection: "column" as const,
      alignItems: "stretch",
    },
  },
  uploadPanelCopy: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "2px",
    minWidth: 0,
  },
  uploadPanelTitle: {
    margin: 0,
    color: COLORS.textPrimary,
    fontSize: "14px",
    fontWeight: 600,
  },
  uploadPanelHint: {
    margin: 0,
    color: "rgba(51, 51, 51, 0.55)",
    fontSize: "12px",
    lineHeight: 1.4,
  },
  hiddenFileInput: {
    display: "none",
  },
  chooseFileButton: {
    minWidth: "140px",
    height: "40px",
    flexShrink: 0,
    backgroundColor: COLORS.white,
    border: `1px solid ${COLORS.primary} !important`,
    borderRadius: "10px",
    color: `${COLORS.primary} !important`,
    fontSize: "13px !important",
    fontWeight: "700 !important",
    letterSpacing: "0.04em",
    textTransform: "uppercase" as const,
    cursor: "pointer",
    padding: "0 18px !important",
    boxShadow: "none !important",
    "&:hover": {
      backgroundColor: "rgba(209, 91, 6, 0.08)",
      color: COLORS.primary,
      boxShadow: "none !important",
    },
  },
  fileListsRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "14px",
    alignItems: "stretch",
    width: "100%",
    [`@media (max-width: ${MOBILE_MAX}px)`]: {
      gridTemplateColumns: "1fr",
    },
  },
  filePanel: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
    minWidth: 0,
    minHeight: 0,
    padding: "12px 14px",
    borderRadius: "12px",
    border: "1px solid rgba(15, 23, 41, 0.1)",
    backgroundColor: COLORS.white,
    height: "220px",
    maxHeight: "220px",
  },
  filePanelTitle: {
    margin: 0,
    flexShrink: 0,
    color: "rgba(15, 23, 41, 0.55)",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase" as const,
  },
  filePanelBody: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "6px",
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflowY: "auto",
    overflowX: "hidden",
    paddingRight: "2px",
  },
  selectedFileRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
  },
  selectedFileName: {
    flex: 1,
    minWidth: 0,
    color: COLORS.textPrimary,
    fontSize: "13px",
    fontWeight: 500,
    wordBreak: "break-word" as const,
    lineHeight: 1.35,
  },
  deletedUploadedFileName: {
    color: "#9e9e9e",
    fontSize: "13px",
    wordBreak: "break-word" as const,
    lineHeight: 1.35,
  },
  deletedLabel: {
    fontStyle: "italic" as const,
  },
  emptyFileName: {
    color: "rgba(51, 51, 51, 0.55)",
    fontSize: "13px",
    fontStyle: "italic" as const,
  },
  removeFileButton: {
    padding: "2px",
    color: "rgba(15, 23, 41, 0.45)",
    "&:hover": {
      color: COLORS.primary,
      backgroundColor: "rgba(209, 91, 6, 0.08)",
    },
  },
  portfolioSection: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    padding: "12px 14px",
    borderRadius: "12px",
    backgroundColor: "rgba(15, 23, 41, 0.03)",
    border: "1px solid rgba(15, 23, 41, 0.08)",
  },
  portfolioPrompt: {
    margin: 0,
    color: COLORS.textPrimary,
    fontSize: "13px",
    fontWeight: 600,
  },
  portfolioConversionLink: {
    alignSelf: "flex-start",
    color: `${COLORS.primary} !important`,
    fontFamily: "inherit",
    fontSize: "13px !important",
    fontWeight: "700 !important",
    lineHeight: 1.5,
    cursor: "pointer",
    textDecoration: "underline !important",
    background: "none",
    border: "none",
    padding: 0,
    textAlign: "left" as const,
    "&:hover": {
      color: COLORS.primary,
    },
  },
  footerActions: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap" as const,
    paddingTop: "4px",
    borderTop: "1px solid rgba(15, 23, 41, 0.08)",
    marginTop: "2px",
  },
  uploadCancelButton: {
    minWidth: "120px",
    height: "42px",
    backgroundColor: COLORS.white,
    border: `1px solid ${COLORS.primary} !important`,
    borderRadius: "10px",
    color: `${COLORS.primary} !important`,
    fontSize: "13px",
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase" as const,
    cursor: "pointer",
    padding: "0 22px !important",
    boxShadow: "none !important",
    "&:hover": {
      backgroundColor: "rgba(209, 91, 6, 0.08)",
      color: COLORS.primary,
      boxShadow: "none !important",
    },
  },
  uploadSubmitButton: {
    minWidth: "120px",
    height: "42px",
    backgroundColor: COLORS.primary,
    border: "none !important",
    borderRadius: "10px",
    color: `${COLORS.white} !important`,
    fontSize: "13px",
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase" as const,
    cursor: "pointer",
    padding: "0 22px !important",
    boxShadow: "0 6px 16px rgba(209, 91, 6, 0.28) !important",
    "&:hover": {
      backgroundColor: "#b34d05",
      color: COLORS.white,
      border: "none !important",
      boxShadow: "0 8px 18px rgba(209, 91, 6, 0.34) !important",
    },
    "&.Mui-disabled": {
      backgroundColor: "rgba(209, 91, 6, 0.32) !important",
      color: `${COLORS.white} !important`,
      boxShadow: "none !important",
    },
  },
  // Kept for any residual consumers of the previous keys.
  selectedFileLabel: {
    color: COLORS.textPrimary,
    fontSize: "14px",
    fontWeight: 600,
  },
  selectedFileWrap: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    minWidth: 0,
  },
  uploadedFilesSection: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    minWidth: 0,
  },
  filePickerSection: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "10px",
  },
  uploadPdfControls: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    columnGap: "12px",
    rowGap: "10px",
    alignItems: "center",
    width: "100%",
  },
  portfolioConversionPrompt: {
    color: `${COLORS.textPrimary} !important`,
    fontSize: "16px",
    fontWeight: 600,
    lineHeight: 1.4,
    justifySelf: "start",
    whiteSpace: "nowrap" as const,
  },
} as const;

/** Popup chrome used only by Upload File entry points. */
export const uploadFilePopupStyles = {
  paper: {
    width: "100%",
    maxWidth: "760px",
    borderRadius: "16px",
    overflow: "hidden",
    backgroundColor: COLORS.white,
    boxShadow: "0 20px 48px rgba(15, 23, 41, 0.18)",
    maxHeight: "calc(100vh - 32px)",
    display: "flex",
    flexDirection: "column" as const,
  },
  header: {
    backgroundColor: COLORS.white,
    borderBottom: "1px solid rgba(15, 23, 41, 0.08)",
    flexShrink: 0,
  },
  content: {
    padding: "18px 28px 22px",
    backgroundColor: "#fafbfc",
    overflowX: "hidden",
    overflowY: "auto",
    flex: "1 1 auto",
    minHeight: 0,
    [`@media (max-width: ${MOBILE_MAX}px)`]: {
      padding: "14px 16px 16px",
    },
  },
} as const;
