import { COLORS } from "../../common/constants/colors";
import { DESKTOP_MIN, RESPONSIVE_MAX } from "../../common/constants/breakpoints";
import {
  HEADER_HEIGHT,
  SIDEBAR_TOP_OFFSET,
  SIDEBAR_WIDTH,
} from "../../common/constants/layout";

export const styles = {
  sideBar: {
    width: `${SIDEBAR_WIDTH}px`,
    position: "fixed" as const,
    height: `calc(100vh - ${HEADER_HEIGHT}px)`,
    left: 0,
    top: `${SIDEBAR_TOP_OFFSET}px`, // Start below the header
    zIndex: 100,
    overflow: "hidden" as const,
    backgroundColor: COLORS.sidebarBg,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.15), 0 4px 16px rgba(0, 0, 0, 0.1)",
    display: "flex",
    flexDirection: "column" as const,
    fontFamily: "system-ui, Avenir, Helvetica, Arial, sans-serif",
    lineHeight: 1.5,
    fontWeight: 400,
    fontSynthesis: "none",
    textRendering: "optimizeLegibility",
    WebkitFontSmoothing: "antialiased",
    MozOsxFontSmoothing: "grayscale",
    [`@media (max-width: ${RESPONSIVE_MAX}px)`]: {
      display: "none",
    },
  },
  drawerPaper: {
    width: `min(${SIDEBAR_WIDTH}px, 85vw)`,
    backgroundColor: COLORS.sidebarBg,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.15), 0 4px 16px rgba(0, 0, 0, 0.1)",
    [`@media (min-width: ${DESKTOP_MIN}px)`]: {
      display: "none",
    },
  },
  drawerPanel: {
    display: "flex",
    flexDirection: "column" as const,
    height: "100%",
    overflow: "hidden" as const,
    fontFamily: "system-ui, Avenir, Helvetica, Arial, sans-serif",
    lineHeight: 1.5,
    fontWeight: 400,
    fontSynthesis: "none",
    textRendering: "optimizeLegibility",
    WebkitFontSmoothing: "antialiased",
    MozOsxFontSmoothing: "grayscale",
  },
  userInfoContainer: {
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center" as const,
    minHeight: "unset",
    padding: "14px 16px 12px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
    marginBottom: "0",
    marginTop: "8px",
  },
  userName: {
    fontSize: "14px",
    fontWeight: 600,
    color: COLORS.white,
    lineHeight: 1.4,
    width: "100%",
  },
  loginTime: {
    fontSize: "12px",
    color: "rgba(255, 255, 255, 0.7)",
    lineHeight: 1.4,
    marginTop: "4px",
    width: "100%",
  },
  itemList: {
    padding: "12px 0",
    flex: 1,
    overflow: "auto" as const,
  },
  sectionHeader: {
    padding: "8px 16px 4px",
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: "12px",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.5px",
  },
  sidebarItem: {
    padding: "12px 16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center" as const,
    gap: "12px",
    color: COLORS.white,
    fontSize: "14px",
    fontWeight: 500,
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: COLORS.sidebarHoverBg,
      borderRadius: "8px",
    },
  },
  activeItem: {
    backgroundColor: COLORS.primary,
    borderRadius: "8px",
    color: COLORS.white,
    fontWeight: 600,
    "&:hover": {
      backgroundColor: COLORS.primary,
    },
  },
  itemIcon: {
    width: "25px",
    height: "25px",
    color: "inherit",
  },
  logoutContainer: {
    paddingBottom: "10px",
    borderTop: "1px solid rgba(255, 255, 255, 0.1)",
    paddingLeft: "5px",
    marginTop: "auto",
    flexShrink: 0, 
    "&:hover": {
      backgroundColor: COLORS.sidebarHoverBg,
      borderRadius: "8px",
    },
  },
  logoutButton: {
    padding: "12px 16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center" as const,
    gap: "12px",
    color: COLORS.white,
    fontSize: "16px",
    fontWeight: 500,
    transition: "all 0.2s ease",
    borderRadius: "8px",
    width: "100%",   
  },
};
